name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_DOCKER_OPTIONS: "--dns=8.8.8.8"
      AWS_DEFAULT_REGION: eu-north-1  
      TZ: Europe/Tallinn

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t playwright-tests .

    - name: Run Playwright Tests in Docker
      run: |
        docker run --rm \
          -e TZ=$TZ \
          -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
          --dns 8.8.8.8 \
          playwright-tests

    - uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30